apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: server
          image: hexcles/wire-grpc-sample:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          command:
            - java
          args:
            - -jar
            - server.jar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: client
          image: hexcles/wire-grpc-sample:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          command:
            - java
          args:
            - -jar
            - client.jar
            - http://server
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: server.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - name: "retry grpc"
      condition:
        method: POST
      isRetryable: true
